apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: btmagent.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: BtmAgent is the Schema for the btmagents API
      displayName: Btm Agent
      kind: BtmAgent
      name: btmagents.apm.egapm
      version: v1
  description: enables btm and installs agent
  displayName: "make bundle-build bundle-push\rbtmagent"
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - btm
  - egagent
  links:
  - name: Btmagent
    url: https://btmagent.domain
  maintainers:
  - email: narayan@gmail.com
    name: narayan.s
  maturity: alpha
  provider:
    name: narayan.s
  version: 0.0.0
